first_name = input("What is your name? ")
print("Hello " + first_name)
birth_year = input("Enter your birth year ")
age = 2022 - int(birth_year)
print("Your age is " + str(age))
status = input("Are you a student? ")
if status == "yes":
    print(first_name + " is a student")
else:
    print(first_name + " is not a student")
course = input("What are you studing? ")
print("Oh! you are a " + course + " student")
father = input("what is your father's name? ")
print(father + " is " + first_name + "'s father")
print(first_name + "'s full name is " + first_name+ father)
